window.esdocSearchIndex = [
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/$0.js~$0",
    "function/index.html#static-function-$0",
    "<span>$0</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/$0.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~$0",
    "function/index.html#static-function-$0",
    "<span>$0</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/$1.js~$1",
    "function/index.html#static-function-$1",
    "<span>$1</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/$1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~$1",
    "function/index.html#static-function-$1",
    "<span>$1</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/$.js~$",
    "function/index.html#static-function-$",
    "<span>$</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/$.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~complex",
    "class/src/Complex.js~Complex.html",
    "<span>Complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/Complex.js</span>",
    "class"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/complex.js~complex",
    "function/index.html#static-function-Complex",
    "<span>Complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/Complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/complex.js~complex",
    "function/index.html#static-function-Complex",
    "<span>Complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/Complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complexfield.js~complexfield",
    "class/src/ComplexField.js~ComplexField.html",
    "<span>ComplexField</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/ComplexField.js</span>",
    "class"
  ],
  [
    "@aureooms/js-complex/src/zerodivisionerror.js~zerodivisionerror",
    "class/src/ZeroDivisionError.js~ZeroDivisionError.html",
    "<span>ZeroDivisionError</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/ZeroDivisionError.js</span>",
    "class"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/abs.js~abs",
    "function/index.html#static-function-abs",
    "<span>abs</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/abs.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/add.js~add",
    "function/index.html#static-function-add",
    "<span>add</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/add.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~add",
    "function/index.html#static-function-add",
    "<span>add</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/arg.js~arg",
    "function/index.html#static-function-arg",
    "<span>arg</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/arg.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/array/core/binary.js~binary",
    "function/index.html#static-function-binary",
    "<span>binary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/array/core/binary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/binary.js~binary",
    "function/index.html#static-function-binary",
    "<span>binary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/binary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/binary.js~binary",
    "function/index.html#static-function-binary",
    "<span>binary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/binary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/binary.js~binary",
    "function/index.html#static-function-binary",
    "<span>binary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/binary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/array/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/array/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/array/core/complex.js~complex",
    "function/index.html#static-function-complex",
    "<span>complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/array/core/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/complex.js~complex",
    "function/index.html#static-function-complex",
    "<span>complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/complex.js~complex",
    "function/index.html#static-function-complex",
    "<span>complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/complex.js~complex",
    "function/index.html#static-function-complex",
    "<span>complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/con.js~con",
    "function/index.html#static-function-con",
    "<span>con</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/con.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/con.js~con",
    "function/index.html#static-function-con",
    "<span>con</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/con.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/div2.js~div2",
    "function/index.html#static-function-div2",
    "<span>div2</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/div2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/div.js~div",
    "function/index.html#static-function-div",
    "<span>div</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/div.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~div",
    "function/index.html#static-function-div",
    "<span>div</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/div.js~div",
    "function/index.html#static-function-div",
    "<span>div</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/div.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/exp.js~exp",
    "function/index.html#static-function-exp",
    "<span>exp</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/exp.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/fromarray.js~fromarray",
    "function/index.html#static-function-fromarray",
    "<span>fromarray</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/fromarray.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/fromarray.js~fromarray",
    "function/index.html#static-function-fromarray",
    "<span>fromarray</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/fromarray.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~iadd",
    "function/index.html#static-function-iadd",
    "<span>iadd</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~idiv",
    "function/index.html#static-function-idiv",
    "<span>idiv</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/img.js~img",
    "function/index.html#static-function-img",
    "<span>img</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/img.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/img.js~img",
    "function/index.html#static-function-img",
    "<span>img</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/img.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/img.js~img",
    "function/index.html#static-function-img",
    "<span>img</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/img.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~imod",
    "function/index.html#static-function-imod",
    "<span>imod</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~imul",
    "function/index.html#static-function-imul",
    "<span>imul</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~ipow",
    "function/index.html#static-function-ipow",
    "<span>ipow</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/iroot2n.js~iroot2n",
    "function/index.html#static-function-iroot2n",
    "<span>iroot2n</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/iroot2n.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~isub",
    "function/index.html#static-function-isub",
    "<span>isub</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~mod",
    "function/index.html#static-function-mod",
    "<span>mod</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/mul.js~mul",
    "function/index.html#static-function-mul",
    "<span>mul</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/mul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~mul",
    "function/index.html#static-function-mul",
    "<span>mul</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/mul.js~mul",
    "function/index.html#static-function-mul",
    "<span>mul</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/mul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/parse.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/parse.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/parse.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/parse.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/pow.js~pow",
    "function/index.html#static-function-pow",
    "<span>pow</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/pow.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~pow",
    "function/index.html#static-function-pow",
    "<span>pow</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/real.js~real",
    "function/index.html#static-function-real",
    "<span>real</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/real.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/real.js~real",
    "function/index.html#static-function-real",
    "<span>real</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/real.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/real.js~real",
    "function/index.html#static-function-real",
    "<span>real</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/real.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/root2n.js~root2n",
    "function/index.html#static-function-root2n",
    "<span>root2n</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/root2n.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/root2n.js~root2n",
    "function/index.html#static-function-root2n",
    "<span>root2n</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/root2n.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/stringify.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/stringify.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/stringify.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/stringify.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/complex.js~sub",
    "function/index.html#static-function-sub",
    "<span>sub</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/array/core/unary.js~unary",
    "function/index.html#static-function-unary",
    "<span>unary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/array/core/unary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/unary.js~unary",
    "function/index.html#static-function-unary",
    "<span>unary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/unary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/unary.js~unary",
    "function/index.html#static-function-unary",
    "<span>unary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/unary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/unary.js~unary",
    "function/index.html#static-function-unary",
    "<span>unary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/unary.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/cc.js",
    "file/src/CC.js.html",
    "src/CC.js",
    "file"
  ],
  [
    "src/complex_default_display.js",
    "file/src/COMPLEX_DEFAULT_DISPLAY.js.html",
    "src/COMPLEX_DEFAULT_DISPLAY.js",
    "file"
  ],
  [
    "src/complex_default_representation.js",
    "file/src/COMPLEX_DEFAULT_REPRESENTATION.js.html",
    "src/COMPLEX_DEFAULT_REPRESENTATION.js",
    "file"
  ],
  [
    "src/complex.js",
    "file/src/Complex.js.html",
    "src/Complex.js",
    "file"
  ],
  [
    "src/complex.js~complex#__floordiv__",
    "class/src/Complex.js~Complex.html#instance-method-__floordiv__",
    "src/Complex.js~Complex#__floordiv__",
    "method"
  ],
  [
    "src/complex.js~complex#__truediv__",
    "class/src/Complex.js~Complex.html#instance-method-__truediv__",
    "src/Complex.js~Complex#__truediv__",
    "method"
  ],
  [
    "src/complex.js~complex#abs",
    "class/src/Complex.js~Complex.html#instance-method-abs",
    "src/Complex.js~Complex#abs",
    "method"
  ],
  [
    "src/complex.js~complex#add",
    "class/src/Complex.js~Complex.html#instance-method-add",
    "src/Complex.js~Complex#add",
    "method"
  ],
  [
    "src/complex.js~complex#cmp",
    "class/src/Complex.js~Complex.html#instance-method-cmp",
    "src/Complex.js~Complex#cmp",
    "method"
  ],
  [
    "src/complex.js~complex#conjugate",
    "class/src/Complex.js~Complex.html#instance-method-conjugate",
    "src/Complex.js~Complex#conjugate",
    "method"
  ],
  [
    "src/complex.js~complex#constructor",
    "class/src/Complex.js~Complex.html#instance-constructor-constructor",
    "src/Complex.js~Complex#constructor",
    "method"
  ],
  [
    "src/complex.js~complex#copy",
    "class/src/Complex.js~Complex.html#instance-method-copy",
    "src/Complex.js~Complex#copy",
    "method"
  ],
  [
    "src/complex.js~complex#div",
    "class/src/Complex.js~Complex.html#instance-method-div",
    "src/Complex.js~Complex#div",
    "method"
  ],
  [
    "src/complex.js~complex#divide_knowing_divisible_by",
    "class/src/Complex.js~Complex.html#instance-method-divide_knowing_divisible_by",
    "src/Complex.js~Complex#divide_knowing_divisible_by",
    "method"
  ],
  [
    "src/complex.js~complex#divide_knowing_model_contains",
    "class/src/Complex.js~Complex.html#instance-method-divide_knowing_model_contains",
    "src/Complex.js~Complex#divide_knowing_model_contains",
    "method"
  ],
  [
    "src/complex.js~complex#divides",
    "class/src/Complex.js~Complex.html#instance-method-divides",
    "src/Complex.js~Complex#divides",
    "method"
  ],
  [
    "src/complex.js~complex#divmod",
    "class/src/Complex.js~Complex.html#instance-method-divmod",
    "src/Complex.js~Complex#divmod",
    "method"
  ],
  [
    "src/complex.js~complex#eq",
    "class/src/Complex.js~Complex.html#instance-method-eq",
    "src/Complex.js~Complex#eq",
    "method"
  ],
  [
    "src/complex.js~complex#ge",
    "class/src/Complex.js~Complex.html#instance-method-ge",
    "src/Complex.js~Complex#ge",
    "method"
  ],
  [
    "src/complex.js~complex#gt",
    "class/src/Complex.js~Complex.html#instance-method-gt",
    "src/Complex.js~Complex#gt",
    "method"
  ],
  [
    "src/complex.js~complex#iadd",
    "class/src/Complex.js~Complex.html#instance-method-iadd",
    "src/Complex.js~Complex#iadd",
    "method"
  ],
  [
    "src/complex.js~complex#idiv",
    "class/src/Complex.js~Complex.html#instance-method-idiv",
    "src/Complex.js~Complex#idiv",
    "method"
  ],
  [
    "src/complex.js~complex#img",
    "class/src/Complex.js~Complex.html#instance-member-img",
    "src/Complex.js~Complex#img",
    "member"
  ],
  [
    "src/complex.js~complex#imod",
    "class/src/Complex.js~Complex.html#instance-method-imod",
    "src/Complex.js~Complex#imod",
    "method"
  ],
  [
    "src/complex.js~complex#imul",
    "class/src/Complex.js~Complex.html#instance-method-imul",
    "src/Complex.js~Complex#imul",
    "method"
  ],
  [
    "src/complex.js~complex#ipow",
    "class/src/Complex.js~Complex.html#instance-method-ipow",
    "src/Complex.js~Complex#ipow",
    "method"
  ],
  [
    "src/complex.js~complex#isone",
    "class/src/Complex.js~Complex.html#instance-method-isone",
    "src/Complex.js~Complex#isone",
    "method"
  ],
  [
    "src/complex.js~complex#isquare",
    "class/src/Complex.js~Complex.html#instance-method-isquare",
    "src/Complex.js~Complex#isquare",
    "method"
  ],
  [
    "src/complex.js~complex#isub",
    "class/src/Complex.js~Complex.html#instance-method-isub",
    "src/Complex.js~Complex#isub",
    "method"
  ],
  [
    "src/complex.js~complex#iszero",
    "class/src/Complex.js~Complex.html#instance-method-iszero",
    "src/Complex.js~Complex#iszero",
    "method"
  ],
  [
    "src/complex.js~complex#le",
    "class/src/Complex.js~Complex.html#instance-method-le",
    "src/Complex.js~Complex#le",
    "method"
  ],
  [
    "src/complex.js~complex#lt",
    "class/src/Complex.js~Complex.html#instance-method-lt",
    "src/Complex.js~Complex#lt",
    "method"
  ],
  [
    "src/complex.js~complex#mod",
    "class/src/Complex.js~Complex.html#instance-method-mod",
    "src/Complex.js~Complex#mod",
    "method"
  ],
  [
    "src/complex.js~complex#move",
    "class/src/Complex.js~Complex.html#instance-method-move",
    "src/Complex.js~Complex#move",
    "method"
  ],
  [
    "src/complex.js~complex#mul",
    "class/src/Complex.js~Complex.html#instance-method-mul",
    "src/Complex.js~Complex#mul",
    "method"
  ],
  [
    "src/complex.js~complex#ne",
    "class/src/Complex.js~Complex.html#instance-method-ne",
    "src/Complex.js~Complex#ne",
    "method"
  ],
  [
    "src/complex.js~complex#negate",
    "class/src/Complex.js~Complex.html#instance-method-negate",
    "src/Complex.js~Complex#negate",
    "method"
  ],
  [
    "src/complex.js~complex#nonzero",
    "class/src/Complex.js~Complex.html#instance-method-nonzero",
    "src/Complex.js~Complex#nonzero",
    "method"
  ],
  [
    "src/complex.js~complex#opposite",
    "class/src/Complex.js~Complex.html#instance-method-opposite",
    "src/Complex.js~Complex#opposite",
    "method"
  ],
  [
    "src/complex.js~complex#pow",
    "class/src/Complex.js~Complex.html#instance-method-pow",
    "src/Complex.js~Complex#pow",
    "method"
  ],
  [
    "src/complex.js~complex#real",
    "class/src/Complex.js~Complex.html#instance-member-real",
    "src/Complex.js~Complex#real",
    "member"
  ],
  [
    "src/complex.js~complex#representation",
    "class/src/Complex.js~Complex.html#instance-member-representation",
    "src/Complex.js~Complex#representation",
    "member"
  ],
  [
    "src/complex.js~complex#signum",
    "class/src/Complex.js~Complex.html#instance-method-signum",
    "src/Complex.js~Complex#signum",
    "method"
  ],
  [
    "src/complex.js~complex#square",
    "class/src/Complex.js~Complex.html#instance-method-square",
    "src/Complex.js~Complex#square",
    "method"
  ],
  [
    "src/complex.js~complex#sub",
    "class/src/Complex.js~Complex.html#instance-method-sub",
    "src/Complex.js~Complex#sub",
    "method"
  ],
  [
    "src/complex.js~complex#tostring",
    "class/src/Complex.js~Complex.html#instance-method-toString",
    "src/Complex.js~Complex#toString",
    "method"
  ],
  [
    "src/complexfield.js",
    "file/src/ComplexField.js.html",
    "src/ComplexField.js",
    "file"
  ],
  [
    "src/complexfield.js~complexfield#$0",
    "class/src/ComplexField.js~ComplexField.html#instance-method-$0",
    "src/ComplexField.js~ComplexField#$0",
    "method"
  ],
  [
    "src/complexfield.js~complexfield#$1",
    "class/src/ComplexField.js~ComplexField.html#instance-method-$1",
    "src/ComplexField.js~ComplexField#$1",
    "method"
  ],
  [
    "src/complexfield.js~complexfield#$j",
    "class/src/ComplexField.js~ComplexField.html#instance-method-$j",
    "src/ComplexField.js~ComplexField#$j",
    "method"
  ],
  [
    "src/complexfield.js~complexfield#characteristic",
    "class/src/ComplexField.js~ComplexField.html#instance-method-characteristic",
    "src/ComplexField.js~ComplexField#characteristic",
    "method"
  ],
  [
    "src/complexfield.js~complexfield#constructor",
    "class/src/ComplexField.js~ComplexField.html#instance-constructor-constructor",
    "src/ComplexField.js~ComplexField#constructor",
    "method"
  ],
  [
    "src/complexfield.js~complexfield#from",
    "class/src/ComplexField.js~ComplexField.html#instance-method-from",
    "src/ComplexField.js~ComplexField#from",
    "method"
  ],
  [
    "src/complexfield.js~complexfield#from_number",
    "class/src/ComplexField.js~ComplexField.html#instance-method-from_number",
    "src/ComplexField.js~ComplexField#from_number",
    "method"
  ],
  [
    "src/complexfield.js~complexfield#from_string",
    "class/src/ComplexField.js~ComplexField.html#instance-method-from_string",
    "src/ComplexField.js~ComplexField#from_string",
    "method"
  ],
  [
    "src/complexfield.js~complexfield#name",
    "class/src/ComplexField.js~ComplexField.html#instance-member-name",
    "src/ComplexField.js~ComplexField#name",
    "member"
  ],
  [
    "src/complexfield.js~complexfield#representation",
    "class/src/ComplexField.js~ComplexField.html#instance-member-representation",
    "src/ComplexField.js~ComplexField#representation",
    "member"
  ],
  [
    "src/complexfield.js~complexfield#tostring",
    "class/src/ComplexField.js~ComplexField.html#instance-method-toString",
    "src/ComplexField.js~ComplexField#toString",
    "method"
  ],
  [
    "src/zerodivisionerror.js",
    "file/src/ZeroDivisionError.js.html",
    "src/ZeroDivisionError.js",
    "file"
  ],
  [
    "src/zerodivisionerror.js~zerodivisionerror#constructor",
    "class/src/ZeroDivisionError.js~ZeroDivisionError.html#instance-constructor-constructor",
    "src/ZeroDivisionError.js~ZeroDivisionError#constructor",
    "method"
  ],
  [
    "src/zerodivisionerror.js~zerodivisionerror#message",
    "class/src/ZeroDivisionError.js~ZeroDivisionError.html#instance-member-message",
    "src/ZeroDivisionError.js~ZeroDivisionError#message",
    "member"
  ],
  [
    "src/zerodivisionerror.js~zerodivisionerror#tostring",
    "class/src/ZeroDivisionError.js~ZeroDivisionError.html#instance-method-toString",
    "src/ZeroDivisionError.js~ZeroDivisionError#toString",
    "method"
  ],
  [
    "src/cartesian/array/compile.js",
    "file/src/cartesian/array/compile.js.html",
    "src/cartesian/array/compile.js",
    "file"
  ],
  [
    "src/cartesian/array/core/binary.js",
    "file/src/cartesian/array/core/binary.js.html",
    "src/cartesian/array/core/binary.js",
    "file"
  ],
  [
    "src/cartesian/array/core/complex.js",
    "file/src/cartesian/array/core/complex.js.html",
    "src/cartesian/array/core/complex.js",
    "file"
  ],
  [
    "src/cartesian/array/core/index.js",
    "file/src/cartesian/array/core/index.js.html",
    "src/cartesian/array/core/index.js",
    "file"
  ],
  [
    "src/cartesian/array/core/unary.js",
    "file/src/cartesian/array/core/unary.js.html",
    "src/cartesian/array/core/unary.js",
    "file"
  ],
  [
    "src/cartesian/array/index.js",
    "file/src/cartesian/array/index.js.html",
    "src/cartesian/array/index.js",
    "file"
  ],
  [
    "src/cartesian/index.js",
    "file/src/cartesian/index.js.html",
    "src/cartesian/index.js",
    "file"
  ],
  [
    "src/cartesian/kernel/compile.js",
    "file/src/cartesian/kernel/compile.js.html",
    "src/cartesian/kernel/compile.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/$0.js",
    "file/src/cartesian/kernel/core/$0.js.html",
    "src/cartesian/kernel/core/$0.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/$1.js",
    "file/src/cartesian/kernel/core/$1.js.html",
    "src/cartesian/kernel/core/$1.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/abs.js",
    "file/src/cartesian/kernel/core/abs.js.html",
    "src/cartesian/kernel/core/abs.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/add.js",
    "file/src/cartesian/kernel/core/add.js.html",
    "src/cartesian/kernel/core/add.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/arg.js",
    "file/src/cartesian/kernel/core/arg.js.html",
    "src/cartesian/kernel/core/arg.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/con.js",
    "file/src/cartesian/kernel/core/con.js.html",
    "src/cartesian/kernel/core/con.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/div.js",
    "file/src/cartesian/kernel/core/div.js.html",
    "src/cartesian/kernel/core/div.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/div2.js",
    "file/src/cartesian/kernel/core/div2.js.html",
    "src/cartesian/kernel/core/div2.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/exp.js",
    "file/src/cartesian/kernel/core/exp.js.html",
    "src/cartesian/kernel/core/exp.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/index.js",
    "file/src/cartesian/kernel/core/index.js.html",
    "src/cartesian/kernel/core/index.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/iroot2n.js",
    "file/src/cartesian/kernel/core/iroot2n.js.html",
    "src/cartesian/kernel/core/iroot2n.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/mul.js",
    "file/src/cartesian/kernel/core/mul.js.html",
    "src/cartesian/kernel/core/mul.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/parse.js",
    "file/src/cartesian/kernel/core/parse.js.html",
    "src/cartesian/kernel/core/parse.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/pow.js",
    "file/src/cartesian/kernel/core/pow.js.html",
    "src/cartesian/kernel/core/pow.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/root2n.js",
    "file/src/cartesian/kernel/core/root2n.js.html",
    "src/cartesian/kernel/core/root2n.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/stringify.js",
    "file/src/cartesian/kernel/core/stringify.js.html",
    "src/cartesian/kernel/core/stringify.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/sub.js",
    "file/src/cartesian/kernel/core/sub.js.html",
    "src/cartesian/kernel/core/sub.js",
    "file"
  ],
  [
    "src/cartesian/kernel/index.js",
    "file/src/cartesian/kernel/index.js.html",
    "src/cartesian/kernel/index.js",
    "file"
  ],
  [
    "src/cartesian/object/compile.js",
    "file/src/cartesian/object/compile.js.html",
    "src/cartesian/object/compile.js",
    "file"
  ],
  [
    "src/cartesian/object/core/$.js",
    "file/src/cartesian/object/core/$.js.html",
    "src/cartesian/object/core/$.js",
    "file"
  ],
  [
    "src/cartesian/object/core/complex.js",
    "file/src/cartesian/object/core/Complex.js.html",
    "src/cartesian/object/core/Complex.js",
    "file"
  ],
  [
    "src/cartesian/object/core/binary.js",
    "file/src/cartesian/object/core/binary.js.html",
    "src/cartesian/object/core/binary.js",
    "file"
  ],
  [
    "src/cartesian/object/core/complex.js",
    "file/src/cartesian/object/core/complex.js.html",
    "src/cartesian/object/core/complex.js",
    "file"
  ],
  [
    "src/cartesian/object/core/fromarray.js",
    "file/src/cartesian/object/core/fromarray.js.html",
    "src/cartesian/object/core/fromarray.js",
    "file"
  ],
  [
    "src/cartesian/object/core/index.js",
    "file/src/cartesian/object/core/index.js.html",
    "src/cartesian/object/core/index.js",
    "file"
  ],
  [
    "src/cartesian/object/core/parse.js",
    "file/src/cartesian/object/core/parse.js.html",
    "src/cartesian/object/core/parse.js",
    "file"
  ],
  [
    "src/cartesian/object/core/root2n.js",
    "file/src/cartesian/object/core/root2n.js.html",
    "src/cartesian/object/core/root2n.js",
    "file"
  ],
  [
    "src/cartesian/object/core/stringify.js",
    "file/src/cartesian/object/core/stringify.js.html",
    "src/cartesian/object/core/stringify.js",
    "file"
  ],
  [
    "src/cartesian/object/core/unary.js",
    "file/src/cartesian/object/core/unary.js.html",
    "src/cartesian/object/core/unary.js",
    "file"
  ],
  [
    "src/cartesian/object/index.js",
    "file/src/cartesian/object/index.js.html",
    "src/cartesian/object/index.js",
    "file"
  ],
  [
    "src/complex.js",
    "file/src/complex.js.html",
    "src/complex.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/polar/array/compile.js",
    "file/src/polar/array/compile.js.html",
    "src/polar/array/compile.js",
    "file"
  ],
  [
    "src/polar/array/core/binary.js",
    "file/src/polar/array/core/binary.js.html",
    "src/polar/array/core/binary.js",
    "file"
  ],
  [
    "src/polar/array/core/complex.js",
    "file/src/polar/array/core/complex.js.html",
    "src/polar/array/core/complex.js",
    "file"
  ],
  [
    "src/polar/array/core/img.js",
    "file/src/polar/array/core/img.js.html",
    "src/polar/array/core/img.js",
    "file"
  ],
  [
    "src/polar/array/core/index.js",
    "file/src/polar/array/core/index.js.html",
    "src/polar/array/core/index.js",
    "file"
  ],
  [
    "src/polar/array/core/real.js",
    "file/src/polar/array/core/real.js.html",
    "src/polar/array/core/real.js",
    "file"
  ],
  [
    "src/polar/array/core/unary.js",
    "file/src/polar/array/core/unary.js.html",
    "src/polar/array/core/unary.js",
    "file"
  ],
  [
    "src/polar/array/index.js",
    "file/src/polar/array/index.js.html",
    "src/polar/array/index.js",
    "file"
  ],
  [
    "src/polar/index.js",
    "file/src/polar/index.js.html",
    "src/polar/index.js",
    "file"
  ],
  [
    "src/polar/kernel/compile.js",
    "file/src/polar/kernel/compile.js.html",
    "src/polar/kernel/compile.js",
    "file"
  ],
  [
    "src/polar/kernel/core/con.js",
    "file/src/polar/kernel/core/con.js.html",
    "src/polar/kernel/core/con.js",
    "file"
  ],
  [
    "src/polar/kernel/core/div.js",
    "file/src/polar/kernel/core/div.js.html",
    "src/polar/kernel/core/div.js",
    "file"
  ],
  [
    "src/polar/kernel/core/img.js",
    "file/src/polar/kernel/core/img.js.html",
    "src/polar/kernel/core/img.js",
    "file"
  ],
  [
    "src/polar/kernel/core/index.js",
    "file/src/polar/kernel/core/index.js.html",
    "src/polar/kernel/core/index.js",
    "file"
  ],
  [
    "src/polar/kernel/core/mul.js",
    "file/src/polar/kernel/core/mul.js.html",
    "src/polar/kernel/core/mul.js",
    "file"
  ],
  [
    "src/polar/kernel/core/real.js",
    "file/src/polar/kernel/core/real.js.html",
    "src/polar/kernel/core/real.js",
    "file"
  ],
  [
    "src/polar/kernel/index.js",
    "file/src/polar/kernel/index.js.html",
    "src/polar/kernel/index.js",
    "file"
  ],
  [
    "src/polar/object/compile.js",
    "file/src/polar/object/compile.js.html",
    "src/polar/object/compile.js",
    "file"
  ],
  [
    "src/polar/object/core/complex.js",
    "file/src/polar/object/core/Complex.js.html",
    "src/polar/object/core/Complex.js",
    "file"
  ],
  [
    "src/polar/object/core/binary.js",
    "file/src/polar/object/core/binary.js.html",
    "src/polar/object/core/binary.js",
    "file"
  ],
  [
    "src/polar/object/core/complex.js",
    "file/src/polar/object/core/complex.js.html",
    "src/polar/object/core/complex.js",
    "file"
  ],
  [
    "src/polar/object/core/fromarray.js",
    "file/src/polar/object/core/fromarray.js.html",
    "src/polar/object/core/fromarray.js",
    "file"
  ],
  [
    "src/polar/object/core/img.js",
    "file/src/polar/object/core/img.js.html",
    "src/polar/object/core/img.js",
    "file"
  ],
  [
    "src/polar/object/core/index.js",
    "file/src/polar/object/core/index.js.html",
    "src/polar/object/core/index.js",
    "file"
  ],
  [
    "src/polar/object/core/real.js",
    "file/src/polar/object/core/real.js.html",
    "src/polar/object/core/real.js",
    "file"
  ],
  [
    "src/polar/object/core/unary.js",
    "file/src/polar/object/core/unary.js.html",
    "src/polar/object/core/unary.js",
    "file"
  ],
  [
    "src/polar/object/index.js",
    "file/src/polar/object/index.js.html",
    "src/polar/object/index.js",
    "file"
  ]
]