window.esdocSearchIndex = [
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/$0.js~$0",
    "function/index.html#static-function-$0",
    "<span>$0</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/$0.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/$1.js~$1",
    "function/index.html#static-function-$1",
    "<span>$1</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/$1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/$.js~$",
    "function/index.html#static-function-$",
    "<span>$</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/$.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/complex.js~complex",
    "function/index.html#static-function-Complex",
    "<span>Complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/Complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/complex.js~complex",
    "function/index.html#static-function-Complex",
    "<span>Complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/Complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/abs.js~abs",
    "function/index.html#static-function-abs",
    "<span>abs</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/abs.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/add.js~add",
    "function/index.html#static-function-add",
    "<span>add</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/add.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/arg.js~arg",
    "function/index.html#static-function-arg",
    "<span>arg</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/arg.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/array/core/binary.js~binary",
    "function/index.html#static-function-binary",
    "<span>binary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/array/core/binary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/binary.js~binary",
    "function/index.html#static-function-binary",
    "<span>binary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/binary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/binary.js~binary",
    "function/index.html#static-function-binary",
    "<span>binary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/binary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/binary.js~binary",
    "function/index.html#static-function-binary",
    "<span>binary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/binary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/array/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/array/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/compile.js~compile",
    "function/index.html#static-function-compile",
    "<span>compile</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/compile.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/array/core/complex.js~complex",
    "function/index.html#static-function-complex",
    "<span>complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/array/core/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/complex.js~complex",
    "function/index.html#static-function-complex",
    "<span>complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/complex.js~complex",
    "function/index.html#static-function-complex",
    "<span>complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/complex.js~complex",
    "function/index.html#static-function-complex",
    "<span>complex</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/complex.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/con.js~con",
    "function/index.html#static-function-con",
    "<span>con</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/con.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/con.js~con",
    "function/index.html#static-function-con",
    "<span>con</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/con.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/div2.js~div2",
    "function/index.html#static-function-div2",
    "<span>div2</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/div2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/div.js~div",
    "function/index.html#static-function-div",
    "<span>div</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/div.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/div.js~div",
    "function/index.html#static-function-div",
    "<span>div</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/div.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/fromarray.js~fromarray",
    "function/index.html#static-function-fromarray",
    "<span>fromarray</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/fromarray.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/fromarray.js~fromarray",
    "function/index.html#static-function-fromarray",
    "<span>fromarray</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/fromarray.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/img.js~img",
    "function/index.html#static-function-img",
    "<span>img</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/img.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/img.js~img",
    "function/index.html#static-function-img",
    "<span>img</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/img.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/img.js~img",
    "function/index.html#static-function-img",
    "<span>img</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/img.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/iroot2n.js~iroot2n",
    "function/index.html#static-function-iroot2n",
    "<span>iroot2n</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/iroot2n.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/mul.js~mul",
    "function/index.html#static-function-mul",
    "<span>mul</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/mul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/mul.js~mul",
    "function/index.html#static-function-mul",
    "<span>mul</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/mul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/parse.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/parse.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/parse.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/parse.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/real.js~real",
    "function/index.html#static-function-real",
    "<span>real</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/real.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/kernel/core/real.js~real",
    "function/index.html#static-function-real",
    "<span>real</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/kernel/core/real.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/real.js~real",
    "function/index.html#static-function-real",
    "<span>real</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/real.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/root2n.js~root2n",
    "function/index.html#static-function-root2n",
    "<span>root2n</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/root2n.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/root2n.js~root2n",
    "function/index.html#static-function-root2n",
    "<span>root2n</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/root2n.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/stringify.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/stringify.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/stringify.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/stringify.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/kernel/core/sub.js~sub",
    "function/index.html#static-function-sub",
    "<span>sub</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/kernel/core/sub.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/array/core/unary.js~unary",
    "function/index.html#static-function-unary",
    "<span>unary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/array/core/unary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/cartesian/object/core/unary.js~unary",
    "function/index.html#static-function-unary",
    "<span>unary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/cartesian/object/core/unary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/array/core/unary.js~unary",
    "function/index.html#static-function-unary",
    "<span>unary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/array/core/unary.js</span>",
    "function"
  ],
  [
    "@aureooms/js-complex/src/polar/object/core/unary.js~unary",
    "function/index.html#static-function-unary",
    "<span>unary</span> <span class=\"search-result-import-path\">@aureooms/js-complex/src/polar/object/core/unary.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/cartesian/array/compile.js",
    "file/src/cartesian/array/compile.js.html",
    "src/cartesian/array/compile.js",
    "file"
  ],
  [
    "src/cartesian/array/core/binary.js",
    "file/src/cartesian/array/core/binary.js.html",
    "src/cartesian/array/core/binary.js",
    "file"
  ],
  [
    "src/cartesian/array/core/complex.js",
    "file/src/cartesian/array/core/complex.js.html",
    "src/cartesian/array/core/complex.js",
    "file"
  ],
  [
    "src/cartesian/array/core/index.js",
    "file/src/cartesian/array/core/index.js.html",
    "src/cartesian/array/core/index.js",
    "file"
  ],
  [
    "src/cartesian/array/core/unary.js",
    "file/src/cartesian/array/core/unary.js.html",
    "src/cartesian/array/core/unary.js",
    "file"
  ],
  [
    "src/cartesian/array/index.js",
    "file/src/cartesian/array/index.js.html",
    "src/cartesian/array/index.js",
    "file"
  ],
  [
    "src/cartesian/index.js",
    "file/src/cartesian/index.js.html",
    "src/cartesian/index.js",
    "file"
  ],
  [
    "src/cartesian/kernel/compile.js",
    "file/src/cartesian/kernel/compile.js.html",
    "src/cartesian/kernel/compile.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/$0.js",
    "file/src/cartesian/kernel/core/$0.js.html",
    "src/cartesian/kernel/core/$0.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/$1.js",
    "file/src/cartesian/kernel/core/$1.js.html",
    "src/cartesian/kernel/core/$1.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/abs.js",
    "file/src/cartesian/kernel/core/abs.js.html",
    "src/cartesian/kernel/core/abs.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/add.js",
    "file/src/cartesian/kernel/core/add.js.html",
    "src/cartesian/kernel/core/add.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/arg.js",
    "file/src/cartesian/kernel/core/arg.js.html",
    "src/cartesian/kernel/core/arg.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/con.js",
    "file/src/cartesian/kernel/core/con.js.html",
    "src/cartesian/kernel/core/con.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/div.js",
    "file/src/cartesian/kernel/core/div.js.html",
    "src/cartesian/kernel/core/div.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/div2.js",
    "file/src/cartesian/kernel/core/div2.js.html",
    "src/cartesian/kernel/core/div2.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/index.js",
    "file/src/cartesian/kernel/core/index.js.html",
    "src/cartesian/kernel/core/index.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/iroot2n.js",
    "file/src/cartesian/kernel/core/iroot2n.js.html",
    "src/cartesian/kernel/core/iroot2n.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/mul.js",
    "file/src/cartesian/kernel/core/mul.js.html",
    "src/cartesian/kernel/core/mul.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/parse.js",
    "file/src/cartesian/kernel/core/parse.js.html",
    "src/cartesian/kernel/core/parse.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/root2n.js",
    "file/src/cartesian/kernel/core/root2n.js.html",
    "src/cartesian/kernel/core/root2n.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/stringify.js",
    "file/src/cartesian/kernel/core/stringify.js.html",
    "src/cartesian/kernel/core/stringify.js",
    "file"
  ],
  [
    "src/cartesian/kernel/core/sub.js",
    "file/src/cartesian/kernel/core/sub.js.html",
    "src/cartesian/kernel/core/sub.js",
    "file"
  ],
  [
    "src/cartesian/kernel/index.js",
    "file/src/cartesian/kernel/index.js.html",
    "src/cartesian/kernel/index.js",
    "file"
  ],
  [
    "src/cartesian/object/compile.js",
    "file/src/cartesian/object/compile.js.html",
    "src/cartesian/object/compile.js",
    "file"
  ],
  [
    "src/cartesian/object/core/$.js",
    "file/src/cartesian/object/core/$.js.html",
    "src/cartesian/object/core/$.js",
    "file"
  ],
  [
    "src/cartesian/object/core/complex.js",
    "file/src/cartesian/object/core/Complex.js.html",
    "src/cartesian/object/core/Complex.js",
    "file"
  ],
  [
    "src/cartesian/object/core/binary.js",
    "file/src/cartesian/object/core/binary.js.html",
    "src/cartesian/object/core/binary.js",
    "file"
  ],
  [
    "src/cartesian/object/core/complex.js",
    "file/src/cartesian/object/core/complex.js.html",
    "src/cartesian/object/core/complex.js",
    "file"
  ],
  [
    "src/cartesian/object/core/fromarray.js",
    "file/src/cartesian/object/core/fromarray.js.html",
    "src/cartesian/object/core/fromarray.js",
    "file"
  ],
  [
    "src/cartesian/object/core/index.js",
    "file/src/cartesian/object/core/index.js.html",
    "src/cartesian/object/core/index.js",
    "file"
  ],
  [
    "src/cartesian/object/core/parse.js",
    "file/src/cartesian/object/core/parse.js.html",
    "src/cartesian/object/core/parse.js",
    "file"
  ],
  [
    "src/cartesian/object/core/root2n.js",
    "file/src/cartesian/object/core/root2n.js.html",
    "src/cartesian/object/core/root2n.js",
    "file"
  ],
  [
    "src/cartesian/object/core/stringify.js",
    "file/src/cartesian/object/core/stringify.js.html",
    "src/cartesian/object/core/stringify.js",
    "file"
  ],
  [
    "src/cartesian/object/core/unary.js",
    "file/src/cartesian/object/core/unary.js.html",
    "src/cartesian/object/core/unary.js",
    "file"
  ],
  [
    "src/cartesian/object/index.js",
    "file/src/cartesian/object/index.js.html",
    "src/cartesian/object/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/polar/array/compile.js",
    "file/src/polar/array/compile.js.html",
    "src/polar/array/compile.js",
    "file"
  ],
  [
    "src/polar/array/core/binary.js",
    "file/src/polar/array/core/binary.js.html",
    "src/polar/array/core/binary.js",
    "file"
  ],
  [
    "src/polar/array/core/complex.js",
    "file/src/polar/array/core/complex.js.html",
    "src/polar/array/core/complex.js",
    "file"
  ],
  [
    "src/polar/array/core/img.js",
    "file/src/polar/array/core/img.js.html",
    "src/polar/array/core/img.js",
    "file"
  ],
  [
    "src/polar/array/core/index.js",
    "file/src/polar/array/core/index.js.html",
    "src/polar/array/core/index.js",
    "file"
  ],
  [
    "src/polar/array/core/real.js",
    "file/src/polar/array/core/real.js.html",
    "src/polar/array/core/real.js",
    "file"
  ],
  [
    "src/polar/array/core/unary.js",
    "file/src/polar/array/core/unary.js.html",
    "src/polar/array/core/unary.js",
    "file"
  ],
  [
    "src/polar/array/index.js",
    "file/src/polar/array/index.js.html",
    "src/polar/array/index.js",
    "file"
  ],
  [
    "src/polar/index.js",
    "file/src/polar/index.js.html",
    "src/polar/index.js",
    "file"
  ],
  [
    "src/polar/kernel/compile.js",
    "file/src/polar/kernel/compile.js.html",
    "src/polar/kernel/compile.js",
    "file"
  ],
  [
    "src/polar/kernel/core/con.js",
    "file/src/polar/kernel/core/con.js.html",
    "src/polar/kernel/core/con.js",
    "file"
  ],
  [
    "src/polar/kernel/core/div.js",
    "file/src/polar/kernel/core/div.js.html",
    "src/polar/kernel/core/div.js",
    "file"
  ],
  [
    "src/polar/kernel/core/img.js",
    "file/src/polar/kernel/core/img.js.html",
    "src/polar/kernel/core/img.js",
    "file"
  ],
  [
    "src/polar/kernel/core/index.js",
    "file/src/polar/kernel/core/index.js.html",
    "src/polar/kernel/core/index.js",
    "file"
  ],
  [
    "src/polar/kernel/core/mul.js",
    "file/src/polar/kernel/core/mul.js.html",
    "src/polar/kernel/core/mul.js",
    "file"
  ],
  [
    "src/polar/kernel/core/real.js",
    "file/src/polar/kernel/core/real.js.html",
    "src/polar/kernel/core/real.js",
    "file"
  ],
  [
    "src/polar/kernel/index.js",
    "file/src/polar/kernel/index.js.html",
    "src/polar/kernel/index.js",
    "file"
  ],
  [
    "src/polar/object/compile.js",
    "file/src/polar/object/compile.js.html",
    "src/polar/object/compile.js",
    "file"
  ],
  [
    "src/polar/object/core/complex.js",
    "file/src/polar/object/core/Complex.js.html",
    "src/polar/object/core/Complex.js",
    "file"
  ],
  [
    "src/polar/object/core/binary.js",
    "file/src/polar/object/core/binary.js.html",
    "src/polar/object/core/binary.js",
    "file"
  ],
  [
    "src/polar/object/core/complex.js",
    "file/src/polar/object/core/complex.js.html",
    "src/polar/object/core/complex.js",
    "file"
  ],
  [
    "src/polar/object/core/fromarray.js",
    "file/src/polar/object/core/fromarray.js.html",
    "src/polar/object/core/fromarray.js",
    "file"
  ],
  [
    "src/polar/object/core/img.js",
    "file/src/polar/object/core/img.js.html",
    "src/polar/object/core/img.js",
    "file"
  ],
  [
    "src/polar/object/core/index.js",
    "file/src/polar/object/core/index.js.html",
    "src/polar/object/core/index.js",
    "file"
  ],
  [
    "src/polar/object/core/real.js",
    "file/src/polar/object/core/real.js.html",
    "src/polar/object/core/real.js",
    "file"
  ],
  [
    "src/polar/object/core/unary.js",
    "file/src/polar/object/core/unary.js.html",
    "src/polar/object/core/unary.js",
    "file"
  ],
  [
    "src/polar/object/index.js",
    "file/src/polar/object/index.js.html",
    "src/polar/object/index.js",
    "file"
  ]
]